# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 17:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('rangeFrom', models.IntegerField()),
                ('rangeTo', models.IntegerField()),
                ('region', models.CharField(max_length=25)),
                ('belongTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='website.History')),
            ],
        ),
    ]
