# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160713_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='featurePicture',
            field=models.ImageField(default='#', upload_to='%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='historyperiod',
            name='featurePicture',
            field=models.ImageField(default='#', max_length=150, upload_to='%Y%m%d'),
        ),
    ]
