# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160713_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyperiod',
            name='summary',
            field=models.TextField(default='#'),
        ),
    ]
