# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_historyperiod_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyperiod',
            name='description',
        ),
        migrations.AlterField(
            model_name='historyperiod',
            name='rangeFrom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historyperiod',
            name='rangeTo',
            field=models.CharField(max_length=20),
        ),
    ]
