# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 17:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160723_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('year', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=25)),
                ('belongTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.HistoryPeriod')),
            ],
        ),
    ]
